"""Add name field to RssFeed

Revision ID: a6aeee8ed8ee
Revises: 74236c0dfb0e
Create Date: 2025-04-15 22:42:35.509788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6aeee8ed8ee'
down_revision: Union[str, None] = '74236c0dfb0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rss_feeds', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rss_feeds', 'name')
    # ### end Alembic commands ###
